"""Phase F: figures, LaTeX tables, and result macros generated from canonical artifacts."""
from __future__ import annotations

import datetime
import json
import time
from pathlib import Path

import numpy as np
import pandas as pd

from . import provenance

MODEL_SHORT = {
    "word_logistic_regression": "M1",
    "character_linear_svm": "M2",
    "structural_logistic_regression": "M3",
    "word_xgboost": "M4",
    "word_noanon_logistic_regression": "A1",
    "character_noanon_linear_svm": "A2",
}


def _header_comment(run_id: str, source_artifact: str) -> str:
    return ("% Generated by deceptive-email manuscript.py\n"
            f"% run_id: {run_id}\n"
            f"% timestamp_utc: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
            f"% source_artifact: {source_artifact}\n")


def _fmt(x, ndigits: int = 3) -> str:
    return f"{x:.{ndigits}f}" if isinstance(x, (int, float, np.floating)) else str(x)


def _esc(s) -> str:
    return str(s).replace("%", "\\%").replace("_", "\\_").replace("&", "\\&").replace("#", "\\#")


def generate_dataset_table(clean: pd.DataFrame, run_id: str, out_dir: Path) -> Path:
    cross = pd.crosstab(clean["source"].astype(str), clean["label"])
    cross.columns = ["benign", "positive"]
    cross = cross.reset_index()
    total = pd.DataFrame([{"source": "Total",
                           "benign": int((clean["label"] == 0).sum()),
                           "positive": int((clean["label"] == 1).sum())}])
    cross = pd.concat([cross, total], ignore_index=True)
    cross["total"] = cross["benign"] + cross["positive"]

    lines = [_header_comment(run_id, "outputs/audit/source_class_distribution.csv")]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Source composition of the cleaned MeAJOR v2.0 dataset "
                 "(after exact-text deduplication).}")
    lines.append("\\label{tab:dataset}")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\hline\\hline")
    lines.append("Source & Benign & Positive & Total \\\\")
    lines.append("\\hline")
    for _, row in cross.iterrows():
        lines.append(f"{_esc(row['source'])} & {row['benign']:,} & {row['positive']:,} & {row['total']:,} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path = out_dir / "dataset_table.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_performance_table(metrics: pd.DataFrame, run_id: str, out_dir: Path) -> Path:
    lines = [_header_comment(run_id, "outputs/runs/<run_id>/metrics/all_metrics.csv")]
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Main performance by model and split protocol. CI is a "
                 "stratified-bootstrap 95\\% interval over 1{,}000 replicates.}")
    lines.append("\\label{tab:performance}")
    lines.append("\\begin{tabular}{lllcccc}")
    lines.append("\\hline\\hline")
    lines.append("Model & Protocol & Split & Macro-F1 (95\\% CI) & Prec.+ & Rec.+ & MCC \\\\")
    lines.append("\\hline")
    for _, row in metrics.iterrows():
        m = MODEL_SHORT.get(row["model_id"], row["model_id"])
        protocol = "random" if row["protocol"] == "random" else "source-disjoint"
        split_label = _esc(str(row["split_id"]))
        ci = f"{row['macro_f1']:.3f} [{row['macro_f1_ci_low']:.3f}, {row['macro_f1_ci_high']:.3f}]"
        lines.append(f"{m} & {protocol} & {split_label} & {ci} & "
                     f"{row['precision_pos']:.3f} & {row['recall_pos']:.3f} & {row['mcc']:.3f} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")
    path = out_dir / "performance_table.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_efficiency_table(eff: pd.DataFrame, run_id: str, out_dir: Path) -> Path:
    lines = [_header_comment(run_id, "outputs/runs/<run_id>/metrics/timing.csv")]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Efficiency on the evaluation machine (median across splits, "
                 "three repetitions for inference timing).}")
    lines.append("\\label{tab:efficiency}")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\hline\\hline")
    lines.append("Model & Features & Train (s) & Infer (ms/1k) & Size \\\\")
    lines.append("\\hline")
    for _, row in eff.iterrows():
        m = MODEL_SHORT.get(row["model_id"], row["model_id"])
        size_mb = float(row["serialized_size_mb"])
        if size_mb < 0.01:
            size_str = f"{size_mb * 1024:.1f} KB"
        else:
            size_str = f"{size_mb:.2f} MB"
        lines.append(f"{m} & {int(row['feature_count']):,} & {row['fit_time_s']:.1f} & "
                     f"{row['inference_time_s_per_1000']*1000:.2f} & {size_str} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path = out_dir / "efficiency_table.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_holdout_table(metrics: pd.DataFrame, run_id: str, out_dir: Path) -> Path:
    """Generate two tables: source-disjoint holdouts and their equal-size controls."""
    sub = metrics[metrics["protocol"] == "source_disjoint"]
    ctrl = metrics[(metrics["protocol"] == "random") & (metrics["split_id"].str.contains("_eq_", regex=False))]
    models_in_metrics = [m for m in MODEL_SHORT if m in sub["model_id"].unique()]
    pivot_h = sub.pivot(index="split_id", columns="model_id", values="macro_f1").reset_index()
    pivot_c = ctrl.pivot(index="split_id", columns="model_id", values="macro_f1").reset_index()
    for m in models_in_metrics:
        pivot_h[m] = pivot_h.get(m, np.nan)
        pivot_c[m] = pivot_c.get(m, np.nan)
    split_info = {}
    for _, row in metrics.drop_duplicates("split_id").iterrows():
        split_info[row["split_id"]] = row

    def _render_table(header: str, caption: str, label: str, pivot: pd.DataFrame,
                      id_to_held) -> list[str]:
        rows = []
        for _, row in pivot.iterrows():
            held = id_to_held(row["split_id"])
            cells = [f"{row.get(m, np.nan):.3f}" for m in models_in_metrics]
            rows.append(f"{_esc(held)} & " + " & ".join(cells) + " \\\\")
        return ([_header_comment(run_id, "outputs/runs/<run_id>/metrics/all_metrics.csv"),
                 "\\begin{table}[t]",
                 "\\centering",
                 f"\\caption{{{caption}}}",
                 f"\\label{{{label}}}",
                 "\\begin{tabular}{l" + "c" * len(models_in_metrics) + "}",
                 "\\hline\\hline",
                 header + " & " + " & ".join(MODEL_SHORT[m] for m in models_in_metrics) + " \\\\",
                 "\\hline"] + rows +
                ["\\hline\\hline", "\\end{tabular}", "\\end{table}"])

    def _held_for_holdout(split_id):
        s = split_info[split_id]
        return "|".join(sorted(s["held_out_sources"].split("|")))

    def _held_for_control(split_id):
        matched = split_id.split("_eq_", 1)[-1]
        s = split_info[matched]
        return "|".join(sorted(s["held_out_sources"].split("|")))

    lines = []
    lines += _render_table(
        "Held-out sources",
        "Macro-F1 on each source-disjoint holdout. Six holdouts (every valid single- and pair-source candidate) are shown.",
        "tab:holdout", pivot_h, _held_for_holdout)
    lines.append("")
    lines += _render_table(
        "Matched holdout",
        "Macro-F1 on the equal-size random control for each source-disjoint holdout. Test size matches the corresponding holdout; train is a stratified random sample of all sources.",
        "tab:eqcontrol", pivot_c, _held_for_control)

    path = out_dir / "holdout_table.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_per_model_gap_table(metrics: pd.DataFrame, run_id: str, out_dir: Path) -> Path:
    """Per-model generalisation gap (random_seed42 minus source-disjoint) with
    mean, median, range, worst case, and paired-bootstrap CI."""
    from . import effect_size as es_mod
    gaps = es_mod.compute_all_protocol_gaps(metrics)
    gaps = gaps[gaps["protocol"] == "source_disjoint"]
    lines = [_header_comment(run_id, "outputs/runs/<run_id>/metrics/paired_delta.csv")]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Per-model generalisation gap (random-split macro-F1 minus "
                 "source-disjoint macro-F1) across the six holdouts. CI is a paired "
                 "bootstrap 95\\% interval over 1{,}000 replicates; Wilcoxon p is the "
                 "signed-rank test across holdouts.}")
    lines.append("\\label{tab:per_model_gap}")
    lines.append("\\begin{tabular}{lcccccc}")
    lines.append("\\hline\\hline")
    lines.append("Model & Mean & Median & Min & Max & 95\\% CI & $p$ \\\\")
    lines.append("\\hline")
    for _, row in gaps.iterrows():
        m = MODEL_SHORT.get(row["model_id"], row["model_id"])
        lines.append(f"{m} & {row['mean']:.3f} & {row['median']:.3f} & {row['min']:.3f} & "
                     f"{row['max']:.3f} & [{row['ci_low']:.3f}, {row['ci_high']:.3f}] & "
                     f"{row['wilcoxon_p']:.3f} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path = out_dir / "per_model_gap.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_cluster_leakage_table(run_id: str, out_dir: Path) -> Path:
    """Cross-split SimHash pair counts per protocol per holdout."""
    leak_path = Path("outputs/splits/cluster_leakage.csv")
    if not leak_path.exists():
        return None
    leak = pd.read_csv(leak_path)
    # Keep only source-disjoint, cluster-disjoint, joint, pooled, and fullmatch rows.
    keep = leak[leak["protocol"].isin(
        ["source_disjoint", "cluster_disjoint", "joint_source_cluster_disjoint",
         "random_cluster_disjoint_pooled", "random_fullmatch"])].copy()
    keep["held"] = keep["split_id"].str.split("holdout_", n=1).str[-1].str.replace("_", "|")
    pivot = keep.pivot(index="held", columns="protocol", values="n_pairs").reset_index()
    pivot_rows = keep.pivot(index="held", columns="protocol", values="n_rows_involved").reset_index()
    lines = [_header_comment(run_id, "outputs/splits/cluster_leakage.csv")]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Cross-split exact-SimHash pairs (rows sharing a 64-bit SimHash "
                 "component that straddle the train/test boundary) by protocol. Source-disjoint "
                 "splits still leak cross-source template replication; the cluster-disjoint, "
                 "joint, and pooled cluster-disjoint protocols eliminate them by construction. "
                 "Pair counts are dominated by a few large template families, so the distinct-row "
                 "counts (in parentheses) bound the practical footprint.}")
    lines.append("\\label{tab:cluster_leakage}")
    lines.append("\\begin{tabular}{lccccc}")
    lines.append("\\hline\\hline")
    lines.append("Held-out & Source-disjoint & Cluster-disjoint & Joint & Pooled cluster-disjoint & Random full-match \\\\")
    lines.append("\\hline")
    for _, row in pivot.iterrows():
        held = str(row["held"])
        def _cell(proto):
            v = row.get(proto, 0)
            r = pivot_rows.loc[pivot_rows["held"] == held, proto].iloc[0] if held in set(pivot_rows["held"]) else 0
            if pd.isna(v):
                return "--"
            return f"{int(v):,} ({int(r):,})"
        lines.append(f"{_esc(held)} & {_cell('source_disjoint')} & "
                     f"{_cell('cluster_disjoint')} & {_cell('joint_source_cluster_disjoint')} & "
                     f"{_cell('random_cluster_disjoint_pooled')} & {_cell('random_fullmatch')} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path = out_dir / "cluster_leakage.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_decomposition_table(run_id: str, out_dir: Path) -> Path:
    """Source predictability, PSI/KS, OOV share, and recalibration gain."""
    div_path = Path("outputs/runs") / run_id / "metrics/distribution_divergence.csv"
    cal_path = Path("outputs/runs") / run_id / "metrics/calibration_recalibration.csv"
    if not div_path.exists() or not cal_path.exists():
        return None
    div = pd.read_csv(div_path)
    cal = pd.read_csv(cal_path)
    # Recalibration gain per holdout: mean delta across probabilistic models.
    cal_mean = cal.groupby("split_id")["delta_macro_f1"].mean().reset_index()
    cal_mean.columns = ["split_id", "recal_gain"]
    merged = div.merge(cal_mean, on="split_id", how="left")
    lines = [_header_comment(run_id, "outputs/runs/<run_id>/metrics/distribution_divergence.csv")]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Decomposition of the source-disjoint drop. Source predictability is "
                 "the 3-fold CV accuracy of a source classifier on the training partition (chance "
                 "0.5 for two-source training). PSI and KS quantify train/test TF-IDF divergence; "
                 "OOV is the test-token share absent from the training vocabulary; recalibration "
                 "gain is the mean macro-F1 change from training-only isotonic threshold "
                 "recalibration across probabilistic models.}")
    lines.append("\\label{tab:decomposition}")
    lines.append("\\begin{tabular}{lcccccc}")
    lines.append("\\hline\\hline")
    lines.append("Holdout & Source pred. & PSI & KS & OOV share & Recal. gain \\\\")
    lines.append("\\hline")
    for _, row in merged.iterrows():
        held = str(row["split_id"]).replace("holdout_", "").replace("_", "|")
        sp = f"{row['cv_accuracy']:.3f}" if pd.notna(row.get("cv_accuracy")) else "--"
        psi = f"{row['psi']:.3f}" if pd.notna(row.get("psi")) else "--"
        ks = f"{row['ks_statistic']:.3f}" if pd.notna(row.get("ks_statistic")) else "--"
        oov = f"{row['oov_share']:.3f}" if pd.notna(row.get("oov_share")) else "--"
        rg = f"{row['recal_gain']:+.3f}" if pd.notna(row.get("recal_gain")) else "--"
        lines.append(f"{_esc(held)} & {sp} & {psi} & {ks} & {oov} & {rg} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path = out_dir / "decomposition.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_paired_delta_table(metrics: pd.DataFrame, run_id: str, out_dir: Path) -> Path:
    """Per-model paired delta vs random_seed42 for each protocol."""
    from . import effect_size as es_mod
    gaps = es_mod.compute_all_protocol_gaps(metrics)
    proto_order = ["source_disjoint", "cluster_disjoint", "joint_source_cluster_disjoint",
                   "random_cluster_disjoint_pooled"]
    gaps["proto_rank"] = gaps["protocol"].map({p: i for i, p in enumerate(proto_order)})
    gaps = gaps.sort_values(["proto_rank", "model_id"])
    lines = [_header_comment(run_id, "outputs/runs/<run_id>/metrics/paired_delta.csv")]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Paired macro-F1 delta (random minus protocol) per model per protocol, "
                 "with paired-bootstrap 95\\% CI and Wilcoxon signed-rank p across the six "
                 "holdouts. The pooled cluster-disjoint row isolates template replication "
                 "without source shift.}")
    lines.append("\\label{tab:paired_delta}")
    lines.append("\\begin{tabular}{llccccc}")
    lines.append("\\hline\\hline")
    lines.append("Model & Protocol & Mean $\\Delta$ & Median & 95\\% CI & Cohen's $d$ & $p$ \\\\")
    lines.append("\\hline")
    for _, row in gaps.iterrows():
        m = MODEL_SHORT.get(row["model_id"], row["model_id"])
        proto = row["protocol"].replace("_", " ")
        lines.append(f"{m} & {_esc(proto)} & {row['mean']:.3f} & {row['median']:.3f} & "
                     f"[{row['ci_low']:.3f}, {row['ci_high']:.3f}] & "
                     f"{row['cohen_d']:.2f} & {row['wilcoxon_p']:.3f} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path = out_dir / "paired_delta.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_result_macros(metrics: pd.DataFrame, clean: pd.DataFrame,
                           run_id: str, out_dir: Path) -> Path:
    # Primary random baseline is the seed-42 80/20 split; sensitivity seeds and
    # equal-size controls are reported separately in tables/figures.
    random = metrics[(metrics["protocol"] == "random") & (metrics["split_id"] == "random_seed42")]
    source = metrics[metrics["protocol"] == "source_disjoint"]
    random_best = random.loc[random["macro_f1"].idxmax()]
    source_best = source.loc[source["macro_f1"].idxmax()]
    gap = random_best["macro_f1"] - source_best["macro_f1"]
    n_pos = int((clean["label"] == 1).sum())
    n_neg = int((clean["label"] == 0).sum())
    n_docs = n_pos + n_neg
    n_sources = clean["source"].nunique()
    n_splits = metrics["split_id"].nunique()
    n_models = metrics["model_id"].nunique()
    source_means = source.groupby("model_id")["macro_f1"].mean()
    eq_control = metrics[(metrics["protocol"] == "random") & (metrics["split_id"].str.contains("_eq_", regex=False))]
    eq_control_means = eq_control.groupby("model_id")["macro_f1"].mean()
    primary_random = metrics[(metrics["protocol"] == "random") & (metrics["split_id"] == "random_seed42")]
    primary_random_means = primary_random.groupby("model_id")["macro_f1"].mean()

    lines = [_header_comment(run_id, "outputs/runs/<run_id>/metrics/all_metrics.csv")]
    lines.append(r"\newcommand{\RandomBestMacroFOne}{" + f"{random_best['macro_f1']:.3f}" + "}")
    lines.append(r"\newcommand{\RandomBestMacroFOneCI}{" +
                 f"{random_best['macro_f1_ci_low']:.3f}, {random_best['macro_f1_ci_high']:.3f}" + "}")
    lines.append(r"\newcommand{\SourceBestMacroFOne}{" + f"{source_best['macro_f1']:.3f}" + "}")
    lines.append(r"\newcommand{\SourceBestMacroFOneCI}{" +
                 f"{source_best['macro_f1_ci_low']:.3f}, {source_best['macro_f1_ci_high']:.3f}" + "}")
    lines.append(r"\newcommand{\GeneralisationGap}{" + f"{gap:.3f}" + "}")
    lines.append(r"\newcommand{\RandomBestModel}{" + MODEL_SHORT[random_best["model_id"]] + "}")
    lines.append(r"\newcommand{\SourceBestModel}{" + MODEL_SHORT[source_best["model_id"]] + "}")
    lines.append(r"\newcommand{\RandomBestModelFull}{" +
                 _esc(str(random_best["model_id"]).replace("_", " ")) + "}")
    # Per-model generalisation gap stats (mean/median/range/worst) from paired_delta.
    try:
        from . import effect_size as es_mod
        gaps = es_mod.compute_all_protocol_gaps(metrics)
        gaps_sd = gaps[gaps["protocol"] == "source_disjoint"]
        for _, row in gaps_sd.iterrows():
            m = MODEL_SHORT.get(row["model_id"], row["model_id"])
            tag = m.upper().replace("1", "One").replace("2", "Two").replace("3", "Three").replace("4", "Four")
            lines.append(r"\newcommand{\GapMean" + tag + "}{" + f"{row['mean']:.3f}" + "}")
            lines.append(r"\newcommand{\GapMedian" + tag + "}{" + f"{row['median']:.3f}" + "}")
            lines.append(r"\newcommand{\GapWorst" + tag + "}{" + f"{row['max']:.3f}" + "}")
            lines.append(r"\newcommand{\GapCI" + tag + "}{" +
                         f"{row['ci_low']:.3f}, {row['ci_high']:.3f}" + "}")
        # Mean gap across the six models (mean of per-model means).
        mean_gap = float(gaps_sd["mean"].mean())
        lines.append(r"\newcommand{\MeanGeneralisationGap}{" + f"{mean_gap:.3f}" + "}")
        # Pooled cluster-disjoint mean gap (template replication only, no source shift).
        gaps_pcd = gaps[gaps["protocol"] == "random_cluster_disjoint_pooled"]
        if len(gaps_pcd):
            pcd_mean = float(gaps_pcd["mean"].mean())
            pcd_min = float(gaps_pcd["mean"].min())
            pcd_max = float(gaps_pcd["mean"].max())
            lines.append(r"\newcommand{\PooledClusterGapMean}{" + f"{pcd_mean:.3f}" + "}")
            lines.append(r"\newcommand{\PooledClusterGapMin}{" + f"{pcd_min:.3f}" + "}")
            lines.append(r"\newcommand{\PooledClusterGapMax}{" + f"{pcd_max:.3f}" + "}")
    except Exception:  # noqa: BLE001
        pass
    for m, short in MODEL_SHORT.items():
        if m in source_means.index:
            lines.append(r"\newcommand{\SourceMeanMacroFOne" + short.upper()
                         .replace("1", "One").replace("2", "Two").replace("3", "Three")
                         .replace("4", "Four") + "}{" +
                         f"{source_means[m]:.3f}" + "}")
    for m, short in MODEL_SHORT.items():
        if m in eq_control_means.index:
            lines.append(r"\newcommand{\EqControlMeanMacroFOne" + short.upper()
                         .replace("1", "One").replace("2", "Two").replace("3", "Three")
                         .replace("4", "Four") + "}{" +
                         f"{eq_control_means[m]:.3f}" + "}")
    for m, short in MODEL_SHORT.items():
        if m in primary_random_means.index:
            lines.append(r"\newcommand{\PrimaryRandomMacroFOne" + short.upper()
                         .replace("1", "One").replace("2", "Two").replace("3", "Three")
                         .replace("4", "Four") + "}{" +
                         f"{primary_random_means[m]:.3f}" + "}")
    try:
        from pathlib import Path
        import json
        nd_path = Path("outputs/audit/near_duplicate_analysis.json")
        if nd_path.exists():
            data = json.loads(nd_path.read_text(encoding="utf-8"))
            edc = data.get("exact_duplicate_counts", {})
            ndc = data.get("near_duplicate_counts", {})
            lines.append(r"\newcommand{\NExactDupGroups}{" + f"{edc.get('n_groups_ge2', 0)}" + "}")
            lines.append(r"\newcommand{\NExactDupRows}{" + f"{edc.get('n_rows_in_exact_dup_groups', 0):,}" + "}")
            lines.append(r"\newcommand{\NExactDupCrossGroups}{" + f"{edc.get('n_groups_cross_source', 0)}" + "}")
            lines.append(r"\newcommand{\NExactDupCrossRows}{" + f"{edc.get('n_rows_in_cross_source_groups', 0):,}" + "}")
            lines.append(r"\newcommand{\NNearDupPairs}{" + f"{ndc.get('n_pairs_hamming_le_8', 0):,}" + "}")
            lines.append(r"\newcommand{\NNearDupCrossPairs}{" + f"{ndc.get('n_pairs_cross_source_hamming_le_8', 0):,}" + "}")
            lines.append(r"\newcommand{\NNearDupRows}{" + f"{ndc.get('n_rows_in_near_dup_pairs', 0):,}" + "}")
    except Exception:
        pass
    # Decomposition values used in Results prose (from canonical CSVs).
    try:
        div_path = Path("outputs/runs") / run_id / "metrics/distribution_divergence.csv"
        if div_path.exists():
            div = pd.read_csv(div_path)
            psi_min = float(div["psi"].min())
            psi_max = float(div["psi"].max())
            ks_min = float(div["ks_statistic"].min())
            ks_max = float(div["ks_statistic"].max())
            oov_min = float(div["oov_share"].min())
            oov_max = float(div["oov_share"].max())
            sp_vals = div.loc[div["cv_accuracy"].notna(), "cv_accuracy"]
            sp_min = float(sp_vals.min()) if len(sp_vals) else float("nan")
            sp_max = float(sp_vals.max()) if len(sp_vals) else float("nan")
            lines.append(r"\newcommand{\PSIMin}{" + f"{psi_min:.3f}" + "}")
            lines.append(r"\newcommand{\PSIMax}{" + f"{psi_max:.3f}" + "}")
            lines.append(r"\newcommand{\KSMin}{" + f"{ks_min:.3f}" + "}")
            lines.append(r"\newcommand{\KSMax}{" + f"{ks_max:.3f}" + "}")
            lines.append(r"\newcommand{\OOVMin}{" + f"{oov_min:.3f}" + "}")
            lines.append(r"\newcommand{\OOVMax}{" + f"{oov_max:.3f}" + "}")
            lines.append(r"\newcommand{\SourcePredMin}{" + f"{sp_min:.2f}" + "}")
            lines.append(r"\newcommand{\SourcePredMax}{" + f"{sp_max:.2f}" + "}")
        cal_path = Path("outputs/runs") / run_id / "metrics/calibration_recalibration.csv"
        if cal_path.exists():
            cal = pd.read_csv(cal_path)
            cal_max = float(cal["delta_macro_f1"].max())
            lines.append(r"\newcommand{\RecalMaxGain}{" + f"{cal_max:+.3f}" + "}")
    except Exception:
        pass
    # Wilcoxon p across holdouts (from paired_delta.csv).
    try:
        pd_path = Path("outputs/runs") / run_id / "metrics/paired_delta.csv"
        if pd_path.exists():
            pd_df = pd.read_csv(pd_path)
            sd = pd_df[pd_df["protocol"] == "source_disjoint"]
            if len(sd):
                p = float(sd["wilcoxon_p"].iloc[0])
                lines.append(r"\newcommand{\WilcoxonP}{" + f"{p:.3f}" + "}")
    except Exception:
        pass
    # Secondary-corpus metrics used in Results prose.
    try:
        sec_path = Path("outputs/audit/secondary_corpus_metrics.csv")
        if sec_path.exists():
            sec = pd.read_csv(sec_path)
            sec_map = dict(zip(sec["model_id"], sec["macro_f1"]))
            for m, short in MODEL_SHORT.items():
                if m in sec_map:
                    tag = short.upper().replace("1", "One").replace("2", "Two").replace("3", "Three").replace("4", "Four")
                    lines.append(r"\newcommand{\SecF" + tag + "}{" + f"{sec_map[m]:.3f}" + "}")
            m3 = sec[sec["model_id"] == "structural_logistic_regression"]
            if len(m3):
                lines.append(r"\newcommand{\SecMThreeMCC}{" + f"{m3['mcc'].iloc[0]:.3f}" + "}")
    except Exception:
        pass
    # AUC-table values used in Results prose (from extra_metrics.csv + all_metrics.csv).
    try:
        extra_path = Path("outputs/runs") / run_id / "metrics/extra_metrics.csv"
        metrics_path = Path("outputs/runs") / run_id / "metrics/all_metrics.csv"
        if extra_path.exists() and metrics_path.exists():
            extra = pd.read_csv(extra_path)
            allm = pd.read_csv(metrics_path)
            sd = extra[extra["protocol"] == "source_disjoint"].merge(
                allm[["split_id", "model_id", "macro_f1"]], on=["split_id", "model_id"], how="left")
            m1 = sd[sd["model_id"] == "word_logistic_regression"]
            m4 = sd[sd["model_id"] == "word_xgboost"]
            if len(m1):
                roc_min = float(m1["roc_auc"].min())
                lines.append(r"\newcommand{\MOneROCaucMinNoDigit}{" + f"{roc_min:.2f}" + "}")
                m1_56 = m1[m1["split_id"] == "holdout_trec5_trec6"]
                if len(m1_56):
                    lines.append(r"\newcommand{\MOneFOneTrecNoDigit}{" + f"{m1_56['macro_f1'].iloc[0]:.3f}" + "}")
                    lines.append(r"\newcommand{\MOneBrierTrecNoDigit}{" + f"{m1_56['brier'].iloc[0]:.3f}" + "}")
            if len(m4):
                m4_56 = m4[m4["split_id"] == "holdout_trec5_trec6"]
                if len(m4_56):
                    lines.append(r"\newcommand{\MFourBrierTrecNoDigit}{" + f"{m4_56['brier'].iloc[0]:.3f}" + "}")
    except Exception:
        pass
    lines.append(r"\newcommand{\NDocs}{" + f"{n_docs:,}" + "}")
    lines.append(r"\newcommand{\NPos}{" + f"{n_pos:,}" + "}")
    lines.append(r"\newcommand{\NNeg}{" + f"{n_neg:,}" + "}")
    lines.append(r"\newcommand{\NSources}{" + f"{n_sources}" + "}")
    lines.append(r"\newcommand{\NSplits}{" + f"{n_splits}" + "}")
    lines.append(r"\newcommand{\NModels}{" + f"{n_models}" + "}")
    pos_rate = n_pos / n_docs
    lines.append(r"\newcommand{\PosRate}{" + f"{pos_rate:.3f}" + "}")
    path = out_dir / "result_macros.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_figures(metrics: pd.DataFrame, clean: pd.DataFrame,
                     eff: pd.DataFrame, run_id: str, out_dir: Path) -> list[Path]:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    files = []
    colors = {"word_logistic_regression": "#1f77b4",
              "character_linear_svm": "#ff7f0e",
              "structural_logistic_regression": "#2ca02c",
              "word_xgboost": "#d62728",
              "word_noanon_logistic_regression": "#9467bd",
              "character_noanon_linear_svm": "#8c564b"}

    # Figure 1: source by class counts.
    cross = pd.crosstab(clean["source"].astype(str), clean["label"]).sort_index()
    fig, ax = plt.subplots(figsize=(3.6, 2.4))
    ax.bar(cross.index, cross[0], color="#c9d6e3", label="benign")
    ax.bar(cross.index, cross[1], bottom=cross[0], color="#7a9c5b", label="positive")
    ax.set_ylabel("Emails")
    ax.tick_params(axis="x", rotation=25, labelsize=7)
    ax.legend(fontsize=7, frameon=False)
    fig.tight_layout()
    p = out_dir / "source_class_distribution.pdf"
    fig.savefig(p)
    fig.savefig(out_dir / "source_class_distribution.png", dpi=300)
    plt.close(fig)
    files.append(p)

    # Figure 2: random vs source-disjoint macro-F1 per model.
    models = [m for m in MODEL_SHORT if m in set(metrics["model_id"])]
    random_vals = [metrics[(metrics["model_id"] == m) & (metrics["protocol"] == "random")
                           & (metrics["split_id"] == "random_seed42")]["macro_f1"].max()
                   for m in models]
    holdout_vals = [metrics[(metrics["model_id"] == m) & (metrics["protocol"] == "source_disjoint")]["macro_f1"].values
                    for m in models]
    x = np.arange(len(models))
    w = 0.4
    fig, ax = plt.subplots(figsize=(3.6, 2.4))
    ax.bar(x - w / 2, random_vals, w, color=[colors[m] for m in models], label="random")
    for i, hv in enumerate(holdout_vals):
        for j, v in enumerate(hv):
            ax.plot([i + w / 2], [v], marker="o", markersize=3, color=colors[models[i]])
    ax.set_xticks(x)
    ax.set_xticklabels([MODEL_SHORT[m] for m in models])
    ax.set_ylabel("Macro-F1")
    ax.set_ylim(0, 1)
    ax.legend(loc="lower right", fontsize=7, frameon=False)
    fig.tight_layout()
    p = out_dir / "random_vs_source_disjoint.pdf"
    fig.savefig(p)
    fig.savefig(out_dir / "random_vs_source_disjoint.png", dpi=300)
    plt.close(fig)
    files.append(p)

    # Figure 3: generalisation gap per model per holdout.
    fig, ax = plt.subplots(figsize=(3.6, 2.4))
    pos = 0
    labels = []
    for m in models:
        rv = metrics[(metrics["model_id"] == m) & (metrics["protocol"] == "random")
                     & (metrics["split_id"] == "random_seed42")]["macro_f1"].max()
        for _, row in metrics[(metrics["model_id"] == m) & (metrics["protocol"] == "source_disjoint")].iterrows():
            gap = rv - row["macro_f1"]
            ax.bar([pos], [gap], color=colors[m], width=0.6)
            labels.append(f"{MODEL_SHORT[m]}/{row['split_id'].replace('holdout_','h')}")
            pos += 1
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_xticks(range(pos))
    ax.set_xticklabels(labels, fontsize=6, rotation=30, ha="right")
    ax.set_ylabel("Random F1 minus source-disjoint F1")
    fig.tight_layout()
    p = out_dir / "generalisation_gap.pdf"
    fig.savefig(p)
    fig.savefig(out_dir / "generalisation_gap.png", dpi=300)
    plt.close(fig)
    files.append(p)

    # Figure 4: accuracy-efficiency tradeoff (source-disjoint mean macro-F1 vs inference time).
    fig, ax = plt.subplots(figsize=(3.6, 2.4))
    for m in models:
        f1v = metrics[(metrics["model_id"] == m) & (metrics["protocol"] == "source_disjoint")]["macro_f1"].mean()
        eff_row = eff[eff["model_id"] == m].iloc[0]
        ax.scatter([eff_row["inference_time_s_per_1000"] * 1000], [f1v],
                   color=colors[m], s=60, zorder=3)
        ax.annotate(MODEL_SHORT[m], (eff_row["inference_time_s_per_1000"] * 1000, f1v),
                    textcoords="offset points", xytext=(6, 4), fontsize=8)
    ax.set_xlabel("Inference time (ms per 1,000 messages)")
    ax.set_ylabel("Mean source-disjoint macro-F1")
    ax.grid(True, which="both", alpha=0.3)
    fig.tight_layout()
    p = out_dir / "accuracy_efficiency_tradeoff.pdf"
    fig.savefig(p)
    fig.savefig(out_dir / "accuracy_efficiency_tradeoff.png", dpi=300)
    plt.close(fig)
    files.append(p)

    # Figure 5: protocol comparison (mean macro-F1 by protocol x model, error bars = 95% CI).
    fig, ax = plt.subplots(figsize=(3.6, 2.4))
    protocols = ["random", "random_cluster_disjoint_pooled", "source_disjoint",
                 "cluster_disjoint", "joint_source_cluster_disjoint"]
    proto_labels = ["random", "pooled cluster-disjoint", "source-disjoint",
                    "cluster-disjoint", "joint"]
    x = np.arange(len(models))
    width = 0.15
    colors5 = ["#4c72b0", "#55a868", "#dd8452", "#c44e52", "#8172b2"]
    for pi, proto in enumerate(protocols):
        means = []
        errs = []
        for m in models:
            sub = metrics[(metrics["model_id"] == m) & (metrics["protocol"] == proto)]
            if len(sub) == 0:
                means.append(np.nan)
                errs.append(0.0)
                continue
            means.append(sub["macro_f1"].mean())
            errs.append(sub["macro_f1"].std() / np.sqrt(len(sub)))
        ax.bar(x + (pi - 2) * width, means, width, label=proto_labels[pi],
               yerr=errs, capsize=2, color=colors5[pi])
    ax.set_xticks(x)
    ax.set_xticklabels([MODEL_SHORT[m] for m in models])
    ax.set_ylabel("Mean macro-F1 (across holdouts)")
    ax.set_ylim(0, 1)
    ax.legend(fontsize=5.5, frameon=False, loc="lower right")
    fig.tight_layout()
    p = out_dir / "protocol_comparison.pdf"
    fig.savefig(p)
    fig.savefig(out_dir / "protocol_comparison.png", dpi=300)
    plt.close(fig)
    files.append(p)

    return files


def generate_auc_table(run_id: str, out_dir: Path) -> Path:
    """PR-AUC, ROC-AUC, and Brier for the six source-disjoint holdouts."""
    extra_path = Path("outputs/runs") / run_id / "metrics/extra_metrics.csv"
    if not extra_path.exists():
        return None
    extra = pd.read_csv(extra_path)
    sub = extra[extra["protocol"] == "source_disjoint"].copy()
    sub["held"] = sub["split_id"].str.replace("holdout_", "").str.replace("_", "|")
    sub = sub.sort_values(["held", "model_id"])
    lines = [_header_comment(run_id, "outputs/runs/<run_id>/metrics/extra_metrics.csv")]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Rank-based and calibration metrics on the six source-disjoint "
                 "holdouts. PR-AUC and ROC-AUC use the positive-class probability for "
                 "probabilistic models and the decision score for the linear SVMs (M2, A2); "
                 "Brier is unavailable for the linear SVMs, which do not produce calibrated "
                 "probabilities.}")
    lines.append("\\label{tab:auc}")
    lines.append("\\begin{tabular}{llccc}")
    lines.append("\\hline\\hline")
    lines.append("Held-out & Model & PR-AUC & ROC-AUC & Brier \\\\")
    lines.append("\\hline")
    for _, row in sub.iterrows():
        m = MODEL_SHORT.get(row["model_id"], row["model_id"])
        pr = f"{row['pr_auc']:.3f}" if pd.notna(row.get("pr_auc")) else "--"
        roc = f"{row['roc_auc']:.3f}" if pd.notna(row.get("roc_auc")) else "--"
        br = f"{row['brier']:.3f}" if pd.notna(row.get("brier")) else "--"
        lines.append(f"{_esc(str(row['held']))} & {m} & {pr} & {roc} & {br} \\\\")
    lines.append("\\hline\\hline")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path = out_dir / "auc_table.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    provenance.atomic_write_text(path, "\n".join(lines) + "\n")
    return path


def generate_paper_artifacts(run_id: str, clean: pd.DataFrame, metrics: pd.DataFrame,
                             eff: pd.DataFrame, run_dir: Path, paper_generated: Path,
                             paper_figures: Path) -> dict:
    run_dir = Path(run_dir)
    paper_generated = Path(paper_generated)
    paper_figures = Path(paper_figures)
    paper_generated.mkdir(parents=True, exist_ok=True)
    paper_figures.mkdir(parents=True, exist_ok=True)

    paths = {
        "dataset_table": generate_dataset_table(clean, run_id, paper_generated),
        "performance_table": generate_performance_table(metrics, run_id, paper_generated),
        "efficiency_table": generate_efficiency_table(eff, run_id, paper_generated),
        "holdout_table": generate_holdout_table(metrics, run_id, paper_generated),
        "per_model_gap": generate_per_model_gap_table(metrics, run_id, paper_generated),
        "cluster_leakage": generate_cluster_leakage_table(run_id, paper_generated),
        "decomposition": generate_decomposition_table(run_id, paper_generated),
        "paired_delta": generate_paired_delta_table(metrics, run_id, paper_generated),
        "auc_table": generate_auc_table(run_id, paper_generated),
        "result_macros": generate_result_macros(metrics, clean, run_id, paper_generated),
    }
    fig_dir = run_dir / "figures"
    figures = generate_figures(metrics, clean, eff, run_id, fig_dir)
    copies = []
    import shutil
    for f in figures:
        for ext in (".pdf", ".png"):
            src = f.with_suffix(ext)
            if src.exists():
                dst = paper_figures / src.name
                shutil.copy2(src, dst)
                copies.append(str(dst))
    paths["figures"] = copies
    return paths
